{
  "hash": "21fb9e2de4cbcc0a23d9b27abd4b520e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple linear regression (MLR)\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"01-29-2026\"\ndate-format: \"MMMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 07-mlr-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n## Computational setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(colorblindr)\nlibrary(palmerpenguins)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n## Topics\n\n-   Introduce multiple linear regression\n\n-   Interpret coefficients in multiple linear regression model\n\n-   Compute predictions and associated intervals for multiple linear regression models\n\n# Considering multiple variables\n\n## Data: Palmer penguins {.midi}\n\nThe `penguins` data set contains data for penguins found on three islands in the Palmer Archipelago, Antarctica. Data were collected and made available by [Dr. Kristen Gorman](https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php) and the [Palmer Station, Antarctica LTER](https://pal.lternet.edu/), a member of the [Long Term Ecological Research Network](https://lternet.edu/). These data can be found in the **palmerpenguins** R package.\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 342 × 4\n   body_mass_g flipper_length_mm bill_length_mm species\n         <int>             <int>          <dbl> <fct>  \n 1        3750               181           39.1 Adelie \n 2        3800               186           39.5 Adelie \n 3        3250               195           40.3 Adelie \n 4        3450               193           36.7 Adelie \n 5        3650               190           39.3 Adelie \n 6        3625               181           38.9 Adelie \n 7        4675               195           39.2 Adelie \n 8        3475               193           34.1 Adelie \n 9        4250               190           42   Adelie \n10        3300               186           37.8 Adelie \n# ℹ 332 more rows\n```\n\n\n:::\n:::\n\n\n## Palmer penguins\n\n![Source: https://allisonhorst.github.io/palmerpenguins/](images/clipboard-2049446366.png)\n\n## Variables\n\n**Predictors**:\n\n-   `bill_length_mm`: Bill length in millimeters\n-   `flipper_length_mm`: Flipper length in millimeters\n-   `species`: Adelie, Gentoo, or Chinstrap species\n\n**Response**: `body_mass_g`: Body mass in grams\n\n<br>\n\n**The goal of this analysis is to use the bill length, flipper length, and species to predict body mass.**\n\n## Response: `body_mass_g`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-mlr_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  min| median|  max|  iqr|\n|----:|------:|----:|----:|\n| 2700|   4050| 6300| 1200|\n\n\n:::\n:::\n\n\n## Predictors {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-mlr_files/figure-revealjs/unnamed-chunk-4-1.png){width=100%}\n:::\n:::\n\n\n## Response vs. predictors {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-mlr_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n::: question\nWhy do we want to use a single model with all the predictors instead of 3 separate models?\n:::\n\n# Multiple linear regression\n\n## Multiple linear regression (MLR)\n\nBased on the analysis goals, we will use a **multiple linear regression** model of the following form\n\n$$\n\\begin{aligned}\\widehat{\\text{body_mass_g}} ~ = \n\\hat{\\beta}_0 & + \\hat{\\beta}_1 \\times \\text{flipper_length_mm} \\\\ & + \\hat{\\beta}_2 \\times  \\text{species}_1  \\\\\n&+\\hat{\\beta}_3 \\times \\text{species}_2  \\\\ &+ \\hat{\\beta}_4 \\times \\text{bill_length_mm}\n\\end{aligned}\n$$\n\nSimilar to simple linear regression, this model assumes that at each combination of the predictor variables, the values `body_mass_g` follow a Normal distribution.\n\n## Multiple linear regression\n\n**Recall:** The simple linear regression model assumes\n\n$$\nY|X\\sim N(\\beta_0 + \\beta_1 X, \\sigma_{\\epsilon}^2)\n$$\n\n. . .\n\n**Similarly:** The multiple linear regression model assumes\n\n$$\nY|X_1, X_2, \\ldots, X_p \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p, \\sigma_{\\epsilon}^2)\n$$\n\n## Multiple linear regression\n\nAt any combination of the predictors, the mean value of the response $Y$, is\n\n$$\nE(Y|X_1, \\ldots, X_p) = \\beta_0 + \\beta_1 X_{1} + \\beta_2 X_2 + \\dots + \\beta_p X_p\n$$\n\n. . .\n\nUsing multiple linear regression, we can estimate the mean response for any combination of predictors\n\n$$\n\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_{1} + \\hat{\\beta}_2 X_2 + \\dots + \\hat{\\beta}_p X_{p}\n$$\n\n::: aside\nSee [Appendix A.3: Estimating the Coefficients](https://intro-regression.github.io/appendix-linear.html#sec-mlr-estimation-matrix) for details.\n:::\n\n## Model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_fit <- lm(body_mass_g ~ flipper_length_mm + species + \n                bill_length_mm, data = penguins)\n\ntidy(penguin_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term              |  estimate| std.error| statistic| p.value|\n|:-----------------|---------:|---------:|---------:|-------:|\n|(Intercept)       | -3904.387|   529.257|    -7.377|   0.000|\n|flipper_length_mm |    27.429|     3.176|     8.638|   0.000|\n|speciesChinstrap  |  -748.562|    81.534|    -9.181|   0.000|\n|speciesGentoo     |    90.435|    88.647|     1.020|   0.308|\n|bill_length_mm    |    61.736|     7.126|     8.664|   0.000|\n\n\n:::\n:::\n\n\n## Model equation\n\n$$\n\\begin{align}\\widehat{\\text{body_mass_g}} =  -3904.387 &+27.429 \\times \\text{flipper_length_mm}\\\\\n& -748.562 \\times \\text{Chinstrap}\\\\  \n&+ 90.435 \\times \\text{Gentoo}\\\\\n&+ 61.736 \\times \\text{bill_length_mm}\n\\end{align}\n$$\n\n::: callout-note\nWe will talk about why there are two terms in the model for `species` soon!\n:::\n\n## Interpreting $\\hat{\\beta}_j$\n\n::::: panel-tabset\n## Question\n\n:::: midi\n::: appex\nThe coefficient of bill_length_mm is 61.736. Select the best interpretation.\n:::\n\n🔗 <https://forms.office.com/r/eVJuUUkfrP>\n::::\n\n## Submit\n\n```{=html}\n<center><iframe width=\"640px\" height=\"480px\" src=\"https://forms.office.com/r/eVJuUUkfrP?embed=true\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" style=\"border: none; max-width:100%; max-height:100vh\" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe></center>\n```\n:::::\n\n## Interpreting $\\hat{\\beta}_j$\n\nThe estimated coefficient $\\hat{\\beta}_j$ is the expected change in the expected value (mean) of $Y$ when $X_j$ increases by one unit, <i>holding the values of all other predictor variables constant</i>.\n\n. . .\n\n**Example:** The estimated coefficient for `flipper_length_mm` is 27.429. This means for each additional millimeter in a penguin's flipper length, its body mass is expected to be greater by 27.429 grams, on average, holding species and bill length constant.\n\n## Prediction\n\n::: question\nWhat is the predicted body mass for a Gentoo penguin with a flipper length of 200 millimeters and bill length of 45 millimeters?\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n-3904.387 + 27.429 * 200 - 748.562 * 0 + 90.435 * 1 + 61.736 * 45\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4449.968\n```\n\n\n:::\n:::\n\n\n<br>\n\n. . .\n\nThe predicted body mass for a Gentoo penguin with a flipper length of 200 millimeters and bill length of 45 millimeters is 4449.968 grams.\n\n## Prediction, revisited {.midi}\n\nJust like with simple linear regression, we can use the `predict()` function in R to calculate the appropriate intervals for our predicted values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm  = 200, \n  species = \"Gentoo\", \n  bill_length_mm = 45\n)\n\npredict(penguin_fit, new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n4449.955 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nDifference in predicted value due to rounding the coefficients on the previous slide.\n:::\n\n## Confidence interval for $\\hat{\\mu}_y$\n\n::: question\nCalculate a 90% confidence interval for the **estimated mean body mass** a Gentoo penguins with a flipper length of 200 millimeters and bill length of 45 millimeters.\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(penguin_fit, new_penguin, interval = \"confidence\", \n        level = 0.90) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|      fit|      lwr|      upr|\n|--------:|--------:|--------:|\n| 4449.955| 4355.238| 4544.671|\n\n\n:::\n:::\n\n\n## Prediction interval for $\\hat{y}$\n\n::: question\nCalculate a 90% prediction interval for the **estimated body mass** **for an individual** Gentoo penguin with a flipper length of 200 millimeters and bill length of 45 millimeters.\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(penguin_fit, new_penguin, interval = \"prediction\", \n        level = 0.90) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|      fit|      lwr|      upr|\n|--------:|--------:|--------:|\n| 4449.955| 3881.035| 5018.875|\n\n\n:::\n:::\n\n\n## Cautions\n\n-   **Do not extrapolate!** Because there are multiple predictor variables, there is the potential to extrapolate in many directions\n-   The multiple regression model only shows **association, not causality**\n    -   To show causality, you must have a carefully designed experiment or carefully account for confounding variables in an observational study\n\n## Recap\n\n-   Introduced multiple linear regression\n\n-   Interpreted coefficients in multiple linear regression model\n\n-   Computed predictions and associated intervals for multiple linear regression models\n\n## Next class\n\n-   Types of predictors in multiple linear regression model\n\n-   Complete [Lecture 08 prepare](../prepare/prepare-lec08.html)\n",
    "supporting": [
      "07-mlr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}